import { VerticalBox } from "std-widgets.slint";
import { MainMenu } from "./screens/main_menu.slint";
import { OilTemperature } from "./screens/oil_temperature.slint";
import { OilPressure } from "./screens/oil_pressure.slint";
import { LapTimer } from "./screens/lap_timer.slint";

export component App inherits Window {
    title: "Circular Display App";
    width: 240px;
    height: 240px;
    background: #111111;

    property <int> selected_index: 0;   // Current menu item
    property <int> visible_screen_index: 0;   // Current visible screen

    callback move_up();
    callback move_down();
    callback enter();

    move_up() => {
        if(visible_screen_index == 0) {
            // Menu screen
            if (selected_index > 0) {
                selected_index -= 1;
            }
        }
        else if(visible_screen_index == 3) {
            // Lap timer screen
            lap_timer.start_stop();
        }
        
    }
    move_down() => {
        if(visible_screen_index == 0) {
            // Menu screen
            if (selected_index < 2) {
                selected_index += 1;
            }
        }
        else if(visible_screen_index == 3) {
            // Lap timer screen
            lap_timer.reset();
        }
    }
    enter() => {
        if(visible_screen_index == 0) {
            // Menu screen
            visible_screen_index = root.selected_index + 1; // Go to selected screen
        }
        else {
            // Function screen
            visible_screen_index = 0; // Return to menu
        }
    }

    // -----------------------------
    // Keyboard handler
    // -----------------------------
    my-key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                debug("Up pressed");
                move_up();
            };
            if (event.text == Key.DownArrow) {
                debug("Down pressed");
                move_down();
            };
            if (event.text == Key.Return) {
                debug("Enter pressed");
                enter();
            };
            accept
        }
    }

    MainMenu {
        selected_index: selected_index;
        visible: visible_screen_index == 0;
    }

    OilTemperature {
        visible: visible_screen_index == 1;
    }

    OilPressure {
        visible: visible_screen_index == 2;
    }

    lap_timer := LapTimer {
        visible: visible_screen_index == 3;
    }
    
}