
export component MenuItem inherits Rectangle {
    in property <string> text: "";
    in property <bool> selected: false;
    in property <bool> dark_mode: true;
    width: 100%;
    height: 30px;
    background: transparent;
    Text {
        text: parent.text;
        color: parent.selected ? (parent.dark_mode ? #ffffff : #333333) : (parent.dark_mode ? #aaaaaa : #666666);
        font-size: parent.selected ? 20px : 16px;
        font-weight: dark_mode ? 500 : 700;
        horizontal-alignment: center;
        vertical-alignment: center;
        animate color {
            duration: 300ms;
            easing: ease-in-out;
        }
        animate font-size {
            duration: 300ms;
            easing: ease-in-out;
        }
    }
}
