
export component PathElement {

    in property <float> progress: 0.0;
    in property <string> stroke: "#7a7a7a";

    bgpath:= Path {
        stroke: #7a7a7a;
        stroke-width: 10px;

        private property <float> radius: min(self.viewbox-width, self.viewbox-height) / 2 + 10;
        private property <float> start-x: self.viewbox-width / 2;
        private property <float> start-y: self.viewbox-height / 2;

        private property <float> progress: 0.999999;

        viewbox-width: 100;
        viewbox-height: 80;
        width: 100%;
        height: 100%;

        MoveTo {
            x: start-x + radius * sin(360deg);
            y: start-y + radius * cos(360deg);
        }

        ArcTo {
            radius-x: bgpath.radius;
            radius-y: bgpath.radius;
            x: start-x + bgpath.radius * sin(-(bgpath.progress) * 360deg);
            y: start-y + bgpath.radius * cos(-(bgpath.progress) * 360deg);
            sweep: bgpath.progress > 0;
            large-arc: bgpath.progress > 0.5;
        }
    }

    // Moving timer Path
    path := Path {
        stroke: #26ccfa;
        stroke-width: 10px;
        
        private property <float> radius: min(self.viewbox-width, self.viewbox-height) / 2 + 10;
        private property <float> start-x: self.viewbox-width / 2;
        private property <float> start-y: self.viewbox-height / 2;
        private property <float> progress: parent.progress;

        animate progress {
            duration: 200ms;
            easing: linear;
        }

        viewbox-width: 100;
        viewbox-height: 80;
        width: 100%;
        height: 100%;

        MoveTo {
            x: start-x + radius * sin(360deg);
            y: start-y + radius * cos(360deg);
        }

        ArcTo {
            radius-x: path.radius;
            radius-y: path.radius;
            x: start-x + path.radius * sin(-(path.progress) * 360deg);
            y: start-y + path.radius * cos(-(path.progress) * 360deg);
            sweep: path.progress > 0;
            large-arc: path.progress > 0.5;
        }
    }
}
