export component TimeDisplay inherits Text {
    in property <int> seconds: 0;
    in property <bool> dark_mode: true;
    property <bool> blinking: false;
    callback start_stop_blinking();
    start_stop_blinking => {
        if (seconds > 0) {
            blinking = !blinking;
        }
        if (!blinking) {
            self.color = dark_mode ? #ffffff : #333333;
        }
    }
    color: dark_mode ? #ffffff : #333333;
    font-size: 50px;
    text: {
        (floor(seconds / 60) < 10 ? "0" : "") + floor(seconds / 60) + ":" + (Math.mod(seconds, 60) < 10 ? "0" : "") + Math.mod(seconds, 60);
    }
    animate color {
        duration: 100ms;
        easing: ease-in-out;
    }
    blinking_timer := Timer {
        interval: 400ms;
        running: blinking;
        triggered() => {
            if (parent.color == (parent.dark_mode ? #ffffff : #333333)) {
                parent.color = parent.dark_mode ? #ffffff78 : #33333378;
            } else {
                parent.color = parent.dark_mode ? #ffffff : #333333;
            }
        }
    }
}
