import { VerticalBox } from "std-widgets.slint";
import { MenuItem } from "../components/MenuItem.slint";

export component LapTimer {
    width: 240px;
    height: 240px;

    property <int> seconds: 0;
    in property <bool> running: false;

    timer := Timer {
        interval: 1s;
        running: running;
        triggered() => {
            seconds += 1;
        }
    }

    VerticalBox {
        alignment: center;
        padding: 0px;

        Rectangle {
            clip: false;
            height: 50px;
            background: #6771ff;
            Text {
                font-size: 30px;
                text: seconds;
            }
        }
    }
}