import { VerticalBox } from "std-widgets.slint";
import { TimeDisplay } from "../components/TimeDisplay.slint";

export component LapTimer {
    width: 240px;
    height: 240px;

    property <int> seconds: 0;

    callback start_stop();
    callback reset();

    timer := Timer {
        interval: 1s;
        running: false;
        triggered() => {
            seconds += 1;
        }
    }

    start_stop() => {
        debug("Timer startstop called");
        if (timer.running) {
            timer.running = false;
        }
        else {
            timer.running = true;
        }
        time_display.start_stop_blinking();
    }

    reset() => {
        if (!timer.running) {
            time_display.start_stop_blinking();
            seconds = 0;
        }
    }

    VerticalBox {
        alignment: center;
        padding: 0px;

        Rectangle {
            clip: false;
            height: 50px;
            background: #6771ff;

            time_display := TimeDisplay {
                seconds: seconds;
            }
        }
    }
}