import { VerticalBox } from "std-widgets.slint";

export component OilPressure {
    in property <int> pressure;
    in property <bool> dark_mode: true;
    width: 240px;
    height: 240px;
    bgpath := Path {
        stroke: #7a7a7a;
        stroke-width: 10px;
        private property <float> radius: min(self.viewbox-width, self.viewbox-height) / 2 + 10;
        private property <float> start-x: self.viewbox-width / 2;
        private property <float> start-y: self.viewbox-height / 2;
        viewbox-width: 100;
        viewbox-height: 80;
        width: 100%;
        height: 100%;
        MoveTo {
            x: start-x + radius * sin(300deg);
            y: start-y + radius * cos(300deg);
        }

        ArcTo {
            radius-x: bgpath.radius;
            radius-y: bgpath.radius;
            x: start-x + bgpath.radius * sin(60deg);
            y: start-y + bgpath.radius * cos(60deg);
            sweep: true;
            large-arc: true;
        }
    }

    Text {
        color: dark_mode ? #ffffff : #333333;
        font-size: 50px;
        text: pressure + "psi";
    }

    Text {
        text: "OIL PRESSURE";
        font-size: 16px;
        color: #7a7a7a;
        x: (parent.width - self.width) / 2;
        y: parent.height - 50px;
    }
}
