import { VerticalBox } from "std-widgets.slint";
import { MenuItem } from "../components/MenuItem.slint";

export component Settings {
    width: 240px;
    height: 240px;
    property <int> selected_index: 0;
    property <[{id: int, name: string}]> menu_items: [
        { id: 0, name: "Return to menu" },
        { id: 1, name: "Dark mode - on" },
        { id: 2, name: "Accent color - blue" },
        { id: 3, name: "Default screen - menu" }
    ];
    callback move_up();
    callback move_down();
    callback enter();
    callback return_to_menu(); // Callback to notify parent to return to main menu
    move_up() => {
        if (selected_index > 0) {
            selected_index -= 1;
        }
    }
    move_down() => {
        if (selected_index < menu_items.length - 1) {
            selected_index += 1;
        }
    }
    enter() => {
        if (selected_index == 0) {
            // Return to main menu
            return_to_menu();
        }
    }
    VerticalBox {
        spacing: 25px;
        y: (self.height / 2) - (55 / 2) * 1px - (selected_index * 55) * 1px;
        animate y {
            duration: 300ms;
            easing: ease-in-out;
        }
        for item in root.menu_items: MenuItem {
            text: item.name;
            selected: selected_index == item.id;
        }
    }
}
